openapi: 3.0.0
info:
  title: Therapy Management API
  version: 1.0.0
  description: API for managing clients, therapists, journals, and access requests.

servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [client, therapist]
      responses:
        201:
          description: User registered successfully
        400:
          description: Invalid request

  /auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login successful
        401:
          description: Invalid credentials

  /journals:
    post:
      summary: Create a new journal
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        201:
          description: Journal created
        401:
          description: Unauthorized

  /journals/{journalId}/revoke-access:
    put:
      summary: Revoke access to a journal
      parameters:
        - name: journalId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        200:
          description: Access revoked
        401:
          description: Unauthorized
        404:
          description: Journal not found

  /access-requests/{requestId}/approve:
    post:
      summary: Approve an access request
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        200:
          description: Request approved
        403:
          description: Unauthorized
        404:
          description: Request not found

  /access-requests/{requestId}/reject:
    post:
      summary: Reject an access request
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        200:
          description: Request rejected
        403:
          description: Unauthorized
        404:
          description: Request not found

  /therapist-mappings/{mappingId}:
    delete:
      summary: Remove therapist-client mapping
      parameters:
        - name: mappingId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        200:
          description: Mapping deleted
        404:
          description: Mapping not found or unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
